export type LearningMetadata = {
  node_type: "call_outcome" | "persona" | "rebuttal_pattern" | "industry_playbook" | "temporal_pattern" | "journey" | "outcome";
  persona_role?: string;
  company_stage?: string;
  industry?: string;
  objection_type?: string;
  rebuttal_pattern?: string;
  outcome?: string;
  region?: string;
  funding_signal?: string;
  failure_reason?: string;
  channel?: string;
  quarter?: string;
  weekday?: string;
  season?: string;
  trigger?: string;
  account?: string;
  total_calls?: number;
  final_outcome?: string;
};

export type Learning = {
  text: string;
  metadata: LearningMetadata;
};

export const DEMO_LEARNINGS: Learning[] = [
  // ═════════ Prior calls (20) — varied personas × industries × outcomes ═════════
  { text: 'Call with Lena Mahler (Head of Platform) at Vossloh. Objection: "we just renewed Datadog last quarter." Rebuttal pattern: complementary-not-replacement (logs layer beneath APM). Outcome: booked 30min follow-up. Duration: 4m12s. Sentiment: neutral→warm.', metadata: { node_type: "call_outcome", persona_role: "Head of Platform", company_stage: "Series-C", industry: "Manufacturing", objection_type: "incumbent-renewal", rebuttal_pattern: "complementary-not-replacement", outcome: "booked", region: "DACH" } },
  { text: 'Call with Marco Steinhoff (CTO) at Otto Group spinout. Objection: annual contract lock-in, previous vendor 6mo to unwind. Rebuttal: no-lock-pilot, 2-week trial, monthly billing. Outcome: booked. Key trigger: mentioning open-source migration tooling.', metadata: { node_type: "call_outcome", persona_role: "CTO", company_stage: "Spinout", industry: "E-commerce", objection_type: "contract-lock-in", rebuttal_pattern: "no-lock-pilot", outcome: "booked", region: "DACH" } },
  { text: 'Call with Sarah Chen (CTO) at Northwind Robotics. Series-B closed 2 days prior. Objection: contract lock-in (defensive about vendor commitments post-raise). Rebuttal: no-lock-pilot. Booked Thursday 14:00. BANT complete: $180K budget, decision = Sarah+VP Platform, 4-6 week timeline.', metadata: { node_type: "call_outcome", persona_role: "CTO", company_stage: "Series-B", industry: "Robotics", objection_type: "contract-lock-in", rebuttal_pattern: "no-lock-pilot", outcome: "booked", region: "DACH", funding_signal: "Series-B-fresh" } },
  { text: 'Call with Helene Voigt (VP Engineering) at Celonis-spinout. Objection: procurement cycle takes 90 days, Q2 budget not cleared. Rebuttal: monthly-startable (credit-card start, stay under €15k MRR procurement threshold). Outcome: pilot started same week. Converted to paid seat at month 2.', metadata: { node_type: "call_outcome", persona_role: "VP Engineering", company_stage: "Spinout", industry: "Process-Mining", objection_type: "procurement-cycle", rebuttal_pattern: "monthly-startable", outcome: "pilot-started", region: "DACH" } },
  { text: 'Call with Daniel Becker (Head of Data) at Trade Republic. Objection: data residency & on-prem requirement (GDPR, BaFin oversight). Rebuttal: eu-region-byok (Frankfurt deployment, customer-held encryption keys, audit-ready logs). Legal review triggered, 6-week close timeline.', metadata: { node_type: "call_outcome", persona_role: "Head of Data", company_stage: "Late-stage", industry: "FinTech", objection_type: "data-residency", rebuttal_pattern: "eu-region-byok", outcome: "legal-review", region: "DACH" } },
  { text: 'Call with Anika Roth (CTO) at Forto. Objection: "we built it in-house already." Rebuttal: build-vs-maintain-tco (year-2 maintenance = 2.4x build cost, 7 FTEs saved). Outcome: re-engaged for Q3. Win-rate for this pattern on in-house-pride objection: 41%.', metadata: { node_type: "call_outcome", persona_role: "CTO", company_stage: "Late-stage", industry: "Logistics", objection_type: "built-in-house", rebuttal_pattern: "build-vs-maintain-tco", outcome: "re-engaged", region: "DACH" } },
  { text: 'Call with Pavel Kuznetsov (VP Platform) at Personio. Objection: budget frozen until Q1. Rebuttal: budget-flex-pilot (free 30-day pilot, billing starts new fiscal period). Outcome: pilot started immediately, converted. Strong close trigger: "our board-meeting is Feb 15, this avoids delaying 6 weeks."', metadata: { node_type: "call_outcome", persona_role: "VP Platform", company_stage: "Late-stage", industry: "HR-Tech", objection_type: "frozen-budget", rebuttal_pattern: "budget-flex-pilot", outcome: "pilot-started", region: "DACH" } },
  { text: 'Call with Mireille Carron (Head of Engineering) at Doctolib. Objection: vendor fatigue — "we evaluated 3 competitors and they were all the same." Rebuttal: live-demo-not-deck (15min screen-share with their actual stack, no slides). Outcome: booked. Sentiment shift during demo: skeptical→intrigued.', metadata: { node_type: "call_outcome", persona_role: "Head of Engineering", company_stage: "Late-stage", industry: "HealthTech", objection_type: "vendor-fatigue", rebuttal_pattern: "live-demo-not-deck", outcome: "booked", region: "EU" } },
  { text: 'Call with Tomás Ribeiro (CFO) at Infarmed-backed startup. Objection: ROI-first, wants 3-year TCO model. Rebuttal: roi-anchor (customer story: Helix Labs saved €340K/year after 8mo). Outcome: booked with his CEO. Key: reference customer in same industry.', metadata: { node_type: "call_outcome", persona_role: "CFO", company_stage: "Series-A", industry: "HealthTech", objection_type: "roi-proof", rebuttal_pattern: "roi-anchor", outcome: "booked", region: "Iberia" } },
  { text: 'Call with Klara Svensson (CRO) at Klarna-spinout. Objection: "our sales team already has HubSpot sequences." Rebuttal: stack-additive (integrates with HubSpot, augments not replaces). Outcome: booked demo for VP Sales + CRO. Pattern win-rate on stack-already-exists: 55%.', metadata: { node_type: "call_outcome", persona_role: "CRO", company_stage: "Spinout", industry: "FinTech", objection_type: "existing-stack", rebuttal_pattern: "stack-additive", outcome: "booked", region: "Nordics" } },
  { text: 'Call with Matthias König (Founder/CEO) at 12-person logistics startup. Objection: "too early-stage for your tooling." Rebuttal: founder-tier (custom pricing, €500/mo until seed round closed). Outcome: converted to paid, became case-study. Founder became vocal advocate.', metadata: { node_type: "call_outcome", persona_role: "Founder", company_stage: "Seed", industry: "Logistics", objection_type: "too-small", rebuttal_pattern: "founder-tier", outcome: "booked", region: "DACH" } },
  { text: 'Call with Jasmin Arslan (VP Sales) at Babbel-spinout. Objection: "my reps already hate new tools." Rebuttal: silent-co-pilot (agent runs in background, reps see drafts, can ignore). Outcome: pilot started with 3 reps, expanded to 22 after 5 weeks.', metadata: { node_type: "call_outcome", persona_role: "VP Sales", company_stage: "Series-B", industry: "EdTech", objection_type: "rep-adoption", rebuttal_pattern: "silent-co-pilot", outcome: "pilot-started", region: "DACH" } },
  { text: 'Call with Felix Baier (COO) at Ocado-partner DACH. Objection: integration timeline — "our CTO said 6 months minimum." Rebuttal: zero-code-integration (webhook+API, 2hrs setup). Outcome: booked technical-eval call the next day. Agent bypassed the 6mo gate by making it a zero-engineering-time decision.', metadata: { node_type: "call_outcome", persona_role: "COO", company_stage: "Late-stage", industry: "E-commerce", objection_type: "integration-timeline", rebuttal_pattern: "zero-code-integration", outcome: "booked", region: "DACH" } },
  { text: 'Call with Sofia Mendes (CMO) at N26 competitor. Objection: "marketing attribution is a mess, any tool we add makes it worse." Rebuttal: clean-attribution (unified tracking via single snippet, replaces 3 tools). Outcome: discovery call booked. CMO mentioned this matched her board\'s Q2 priority.', metadata: { node_type: "call_outcome", persona_role: "CMO", company_stage: "Series-C", industry: "FinTech", objection_type: "attribution-complexity", rebuttal_pattern: "clean-attribution", outcome: "booked", region: "DACH" } },
  { text: 'Call with Rafael Herrera (Head of Growth) at Cabify. Objection: "we\'ve already tested 4 similar tools this year." Rebuttal: comparison-receipts (case study showing +$1.2M pipeline in 6 months at Uber spinoff). Outcome: booked pilot, 60-day evaluation.', metadata: { node_type: "call_outcome", persona_role: "Head of Growth", company_stage: "Late-stage", industry: "Mobility", objection_type: "test-fatigue", rebuttal_pattern: "comparison-receipts", outcome: "pilot-started", region: "Iberia" } },
  { text: 'Call with Nadia Haddad (Head of Product) at TeamViewer-spinout. Objection: "your AI will hallucinate customer data." Rebuttal: deterministic-outputs (show live audit log, every AI action traceable + human-reviewable). Outcome: booked CTO call. Technical objection resolved in 2 minutes.', metadata: { node_type: "call_outcome", persona_role: "Head of Product", company_stage: "Spinout", industry: "DevTools", objection_type: "ai-trust", rebuttal_pattern: "deterministic-outputs", outcome: "booked", region: "DACH" } },
  { text: 'Call with Simone Bianchi (VP Engineering) at Scalapay. Lost: couldn\'t articulate fit because dossier was thin — only public LinkedIn + 1 press release. Outcome: lost after 3m40s. Learning: research-first dossiers should include: GitHub activity, recent hires, tech-stack diff, investor portfolio adjacency.', metadata: { node_type: "call_outcome", persona_role: "VP Engineering", company_stage: "Series-B", industry: "FinTech", outcome: "lost", failure_reason: "thin-dossier" } },
  { text: 'Call with Mia Johannsen (Head of Operations) at Zalando-partner. Re-engaged after 4-month silence from cold ping. Opener referenced her recent LinkedIn post on supply-chain automation. Outcome: booked. Lesson: 90% of re-engagement wins cite a specific piece of content they shared within the last 14 days.', metadata: { node_type: "call_outcome", persona_role: "Head of Operations", company_stage: "Late-stage", industry: "Fashion-Tech", objection_type: "cold-outreach", rebuttal_pattern: "content-reference", outcome: "re-engaged", region: "DACH" } },
  { text: 'Call with Eugen Patrascu (Principal Engineer) at GoCardless. Gatekeeper redirect — "that\'s CTO territory, not me." Rebuttal: peer-handoff (asked for warm intro, offered to send a write-up he could forward). Outcome: got intro to Head of Platform + booked directly. Gatekeeper pattern win-rate: 48%.', metadata: { node_type: "call_outcome", persona_role: "Principal Engineer", company_stage: "Late-stage", industry: "FinTech", objection_type: "wrong-contact", rebuttal_pattern: "peer-handoff", outcome: "re-engaged", region: "UK-EU" } },
  { text: 'Call with Olga Novak (CIO) at DHL spinoff. Objection: "security review alone takes our InfoSec team 8 weeks." Rebuttal: pre-cleared-vendors (SOC2 Type II + ISO-27001 + pre-filled DORA questionnaire). Outcome: InfoSec bypass approval in 3 days via fast-track. Booked pilot.', metadata: { node_type: "call_outcome", persona_role: "CIO", company_stage: "Enterprise", industry: "Logistics", objection_type: "security-review-timeline", rebuttal_pattern: "pre-cleared-vendors", outcome: "pilot-started", region: "DACH" } },

  // ═════════ Persona dossiers (12) — who they are, what they value ═════════
  { text: 'Persona dossier · CTO at Series-B B2B SaaS. Tends to value: speed, autonomy, engineering-led decisions, clean architecture. Avoids: long procurement, annual lock-in, vendor over-promising. Best opener: reference recent funding + technical specificity. Worst opener: ROI-first pitch or price-anchored pitch.', metadata: { node_type: "persona", persona_role: "CTO", company_stage: "Series-B" } },
  { text: 'Persona dossier · VP Engineering at Late-stage. Values: team velocity, hiring leverage, on-call quality of life, reducing toil. Decision shared with CTO + Head of Platform. Best channels: email-then-phone (not LinkedIn cold). Emotional trigger: mentioning their last DevOps hire or Reddit/HN posts.', metadata: { node_type: "persona", persona_role: "VP Engineering", company_stage: "Late-stage" } },
  { text: 'Persona dossier · Head of Data at FinTech. Always raises GDPR + data residency in first 90 seconds. Need EU-region story locked before any feature pitch. Decision is theirs but legal review is mandatory. Emotional anchor: being seen as "the one who kept us out of trouble."', metadata: { node_type: "persona", persona_role: "Head of Data", company_stage: "Any", industry: "FinTech" } },
  { text: 'Persona dossier · CFO at growth-stage. Filters everything through 2 frames: cash-flow timing, ROI payback window. Best: concrete TCO model, reference-customer ROI, payback under 12mo. Worst: vague "10x productivity" claims. Channel: email first, phone only after ROI established.', metadata: { node_type: "persona", persona_role: "CFO", company_stage: "Growth" } },
  { text: 'Persona dossier · CRO at scaling B2B. Pain: rep quota attainment, sales cycle compression, hiring lag. Values: anything that makes reps more productive without adoption friction. Decides with VP Sales. Best opener: benchmark vs their public hire-velocity. Red flag: "my reps already use X."', metadata: { node_type: "persona", persona_role: "CRO", company_stage: "Growth" } },
  { text: 'Persona dossier · CMO at Series-C. Cares about: brand consistency, attribution clarity, CAC payback. Avoids: anything that muddies brand voice or adds tool sprawl. Decides with Head of Growth + CFO. Best reference: attribution-war-story from peer company.', metadata: { node_type: "persona", persona_role: "CMO", company_stage: "Series-C" } },
  { text: 'Persona dossier · COO at Enterprise. Systems-thinker, risk-averse. Loves: process consolidation, vendor reduction, SLA guarantees. Hates: "vibey" pitches. Always asks: "what does this replace?" Best opener: skip pitch, ask 1 direct question about their ops architecture.', metadata: { node_type: "persona", persona_role: "COO", company_stage: "Enterprise" } },
  { text: 'Persona dossier · Head of Platform. Hybrid engineering+business role. Pain: dev-productivity metrics, internal-customer satisfaction. Values: tooling that makes their platform engineers more effective. Decides with CTO but drives evaluation. Best channel: Slack-in-community (they\'re in Platform Engineering channels).', metadata: { node_type: "persona", persona_role: "Head of Platform", company_stage: "Any" } },
  { text: 'Persona dossier · Founder/CEO at pre-seed to seed. Wears every hat. Values: speed-to-value, founder-friendly pricing, becoming a case study. Decisions are instant. Best: custom founder-tier, personal relationship with your founder. Worst: enterprise-style pitch or long procurement.', metadata: { node_type: "persona", persona_role: "Founder", company_stage: "Seed" } },
  { text: 'Persona dossier · VP Sales at B2B scale-up. Lives in: Salesforce, Gong, email. Values: rep adoption, manager visibility, pipeline predictability. Worst opener: "this will transform your sales process." Best: specific rep-productivity benchmark from peer company.', metadata: { node_type: "persona", persona_role: "VP Sales", company_stage: "Growth" } },
  { text: 'Persona dossier · Head of Product. Pain: shipping velocity, experiment cycle time, user-research turnaround. Best: tool that reduces experimentation friction. Decides with Engineering. Red flag: anything that adds to their stack without obvious replacement story.', metadata: { node_type: "persona", persona_role: "Head of Product", company_stage: "Any" } },
  { text: 'Persona dossier · Principal Engineer / Staff Engineer. Often not the decider but heavily influences. Best: technical depth, GitHub-visible reputation, respect their opinion. Worst: marketing-speak or "business value" framing. Channel: technical blog post or open-source PR gets further than email.', metadata: { node_type: "persona", persona_role: "Principal Engineer", company_stage: "Any" } },

  // ═════════ Rebuttal patterns (15) — with win-rates + when to use ═════════
  { text: 'Pattern · no-lock-pilot → for: post-raise CTOs, scaling teams, teams burned by previous vendor. Mechanic: 2-week pilot on one cluster/team, monthly billing, open-source migration tooling. Average lift: +73% on contract-lock-in objections for CTO persona. Do NOT use on: procurement-locked enterprises.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "no-lock-pilot" } },
  { text: 'Pattern · complementary-not-replacement → for: teams who just renewed an incumbent. Mechanic: position in adjacent layer (logs vs APM, CRM-enrichment vs CRM), no migration required, triggers expand-not-replace mental model. Lift: +64% on incumbent-renewal objections.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "complementary-not-replacement" } },
  { text: 'Pattern · eu-region-byok → for: FinTech, HealthTech, regulated. Mechanic: Frankfurt or Dublin deployment, customer-held encryption keys, audit-ready logs, pre-filled DORA/DPIA docs. Lift: +58% on data-residency objections. Required for DACH FinTech.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "eu-region-byok" } },
  { text: 'Pattern · monthly-startable → for: avoiding 90-day procurement cycles. Mechanic: stay under company procurement threshold (€15k MRR typical), credit card start, upgrade contract later. Lift: +81% on procurement-cycle objections.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "monthly-startable" } },
  { text: 'Pattern · live-demo-not-deck → for: vendor-fatigued buyers. Mechanic: 15min unscripted screen-share against their actual stack, no slides. Opens with: "instead of a pitch, let\'s put your X in front of this." Lift: +77%.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "live-demo-not-deck" } },
  { text: 'Pattern · build-vs-maintain-tco → for: teams who built in-house. Mechanic: TCO model showing year-2 maintenance load = 2.4x build cost, 7 FTEs saved. Lift: +41% (lower because emotional attachment to in-house). Always acknowledge their craftsmanship first.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "build-vs-maintain-tco" } },
  { text: 'Pattern · budget-flex-pilot → for: frozen Q1/Q4 budgets. Mechanic: free 30-day pilot, billing starts new fiscal period, purchase order signed now for budget-planning optics. Lift: +69%.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "budget-flex-pilot" } },
  { text: 'Pattern · roi-anchor → for: CFO/finance-led evaluations. Mechanic: specific peer-company ROI story with concrete numbers (e.g., "Helix Labs saved €340K/year after 8mo, payback in month 6"). Lift: +52% on roi-proof objections.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "roi-anchor" } },
  { text: 'Pattern · stack-additive → for: "we already use X." Mechanic: position as augmentation layer, integrates with existing tool, no rip-and-replace. Lift: +55% on existing-stack objections.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "stack-additive" } },
  { text: 'Pattern · founder-tier → for: pre-seed/seed startups. Mechanic: custom tier at €500-1500/mo until funding round closes, becomes case study. Lift: +88% on too-small objections. Risky: scales poorly, cap at 20 accounts.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "founder-tier" } },
  { text: 'Pattern · silent-co-pilot → for: rep-adoption fears. Mechanic: agent runs in background, reps see drafts they can ignore, opt-in not mandate. Lift: +67% on rep-adoption objections. Starts with 3 reps, expands organically.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "silent-co-pilot" } },
  { text: 'Pattern · zero-code-integration → for: "integration will take months." Mechanic: webhook + API, 2-hour setup, no CI/CD changes. Lift: +71% on integration-timeline objections.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "zero-code-integration" } },
  { text: 'Pattern · clean-attribution → for: marketing tool sprawl. Mechanic: single snippet replaces 3+ tracking tools, unified dashboard. Lift: +48% on attribution-complexity.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "clean-attribution" } },
  { text: 'Pattern · comparison-receipts → for: test-fatigued buyers. Mechanic: side-by-side benchmark vs 3 named competitors with peer-company results. Lift: +54% on test-fatigue.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "comparison-receipts" } },
  { text: 'Pattern · deterministic-outputs → for: AI-trust objections. Mechanic: every AI action is human-reviewable, audit log, full provenance chain. Lift: +63% on ai-trust objections. Critical for FinTech, HealthTech, regulated.', metadata: { node_type: "rebuttal_pattern", rebuttal_pattern: "deterministic-outputs" } },

  // ═════════ Industry playbooks (8) ═════════
  { text: 'Industry playbook · FinTech → gatekeepers: Head of Data, InfoSec, Legal. Required: EU-region deployment, BYOK, SOC2+ISO-27001, pre-filled DORA questionnaire. Buying cycle: 8-14 weeks. Top objection: data-residency. Top rebuttal: eu-region-byok.', metadata: { node_type: "industry_playbook", industry: "FinTech" } },
  { text: 'Industry playbook · HealthTech → gatekeepers: CMO, Head of Compliance, CTO. Required: HIPAA/GDPR dual-compliance, patient-data encryption, audit trail. Buying cycle: 12-20 weeks. Top objection: regulatory-risk. Top rebuttal: deterministic-outputs + eu-region-byok.', metadata: { node_type: "industry_playbook", industry: "HealthTech" } },
  { text: 'Industry playbook · E-commerce → decision-makers: COO, Head of Growth. Speed-obsessed. Buying cycle: 2-6 weeks. Top objection: "Black Friday freeze" (no changes mid-October-January). Top rebuttal: zero-code-integration. Best time to pitch: February-April or June-August.', metadata: { node_type: "industry_playbook", industry: "E-commerce" } },
  { text: 'Industry playbook · Logistics → decision-makers: COO, CIO, Head of Operations. Risk-averse, SLA-focused. Buying cycle: 10-16 weeks. Top objection: integration-timeline. Top rebuttal: pre-cleared-vendors + zero-code-integration. Reference customers are critical — ideally same vertical.', metadata: { node_type: "industry_playbook", industry: "Logistics" } },
  { text: 'Industry playbook · Manufacturing → decision-makers: Plant Manager, Head of Digital, CIO. Legacy-heavy stacks (SAP, Siemens). Buying cycle: 16-26 weeks. Top objection: "legacy integration." Top rebuttal: stack-additive. Tip: mention on-prem deployment option even if they go cloud.', metadata: { node_type: "industry_playbook", industry: "Manufacturing" } },
  { text: 'Industry playbook · EdTech → decision-makers: Head of Product, VP Engineering. Academic-year cycle: pitch in June-August for Sept rollouts. Top objection: student-privacy. Top rebuttal: deterministic-outputs + COPPA/FERPA compliance. Budget freezes mid-Sept to mid-Jan.', metadata: { node_type: "industry_playbook", industry: "EdTech" } },
  { text: 'Industry playbook · MarTech → decision-makers: CMO, Head of Growth, VP Marketing Ops. Tool sprawl is the meta-pain. Buying cycle: 4-8 weeks. Top objection: existing-stack. Top rebuttal: clean-attribution + stack-additive. Best proof: show you reduce their tool count, not add to it.', metadata: { node_type: "industry_playbook", industry: "MarTech" } },
  { text: 'Industry playbook · DevTools → decision-makers: Staff Eng, Principal Eng, sometimes VP Eng. Tech-savvy, bullshit-allergic. Buying cycle: 3-10 weeks but includes POC. Top objection: ai-trust + integration-timeline. Top rebuttal: deterministic-outputs. GitHub-first marketing beats sales emails.', metadata: { node_type: "industry_playbook", industry: "DevTools" } },

  // ═════════ Temporal patterns (5) ═════════
  { text: 'Temporal pattern · Q1 budget freeze → Jan-Feb most EU companies have frozen non-critical spend pending annual plan. Best rebuttal: budget-flex-pilot. Avoid: pushing hard for signed contract. Best: secure verbal commitment + start pilot billed-later.', metadata: { node_type: "temporal_pattern", quarter: "Q1" } },
  { text: 'Temporal pattern · Q4 end-of-quarter push → reps have quota, buyers know it. Oct-Dec: discount requests spike 40%. Counter: value-anchor vs price-anchor, offer multi-year discount instead of % cut.', metadata: { node_type: "temporal_pattern", quarter: "Q4" } },
  { text: 'Temporal pattern · Series-B announcement window → 14 days after announced funding, CTO is fielding vendor pings. Best opener: specific congratulations + technical reference (not "congrats on the raise"). Lift: +52% on post-raise outreach within 14 days.', metadata: { node_type: "temporal_pattern", trigger: "funding-announcement" } },
  { text: 'Temporal pattern · Board meeting Thursday window → most European startup boards meet Thursdays. Avoid Thursday morning pings. Best window for closing calls: Tuesday+Wednesday afternoon, Thursday afternoon post-board.', metadata: { node_type: "temporal_pattern", weekday: "Thursday" } },
  { text: 'Temporal pattern · Post-vacation re-engagement → Sept (DACH) and early-Jan, dormant deals re-surface. Best opener: reference a specific change they\'d have missed (product update, pricing change, new case study). Avoid generic "hope you had a great summer."', metadata: { node_type: "temporal_pattern", season: "post-vacation" } },

  // ═════════ Multi-call journeys (4) ═════════
  { text: 'Journey · Helix Labs (VP Engineering) → Call 1: cold pitch, objection test-fatigue, outcome: lost. Call 2: 4 weeks later, content-reference opener (LinkedIn post), outcome: discovery call. Call 3: 2 weeks later, comparison-receipts pattern, outcome: pilot-started. Total journey: 43 days. Learning: losing call-1 doesn\'t mean losing the account — the second contact should reference something they posted, not the first call.', metadata: { node_type: "journey", account: "Helix Labs", total_calls: 3, final_outcome: "pilot-started" } },
  { text: 'Journey · Personio (VP Platform → CTO) → Call 1 with VP Platform: peer-handoff pattern, outcome: re-engaged with intro to CTO. Call 2 with CTO: no-lock-pilot, outcome: booked. Call 3 post-pilot: expansion to 3 teams. Total: 62 days. Learning: gatekeeper-bypass via intro is 3x faster than direct CTO ping.', metadata: { node_type: "journey", account: "Personio", total_calls: 3, final_outcome: "expansion" } },
  { text: 'Journey · Trade Republic (Head of Data) → Call 1: eu-region-byok, outcome: legal-review (6wk wait). Call 2: pre-cleared-vendors, outcome: pilot-started. Call 3: expanded to 2 additional teams. Total: 91 days. Learning: FinTech journeys are long but have high expansion ARR.', metadata: { node_type: "journey", account: "Trade Republic", total_calls: 3, final_outcome: "expansion" } },
  { text: 'Journey · Doctolib (Head of Engineering → CTO → Head of Compliance) → Call 1: live-demo-not-deck, outcome: booked. Call 2 with CTO: stack-additive, outcome: technical approval. Call 3 with Compliance: deterministic-outputs, outcome: pilot-started. Total: 48 days. Learning: HealthTech requires 3-persona sell — eng, exec, compliance.', metadata: { node_type: "journey", account: "Doctolib", total_calls: 3, final_outcome: "pilot-started" } },

  // ═════════ Outcomes catalog (4) ═════════
  { text: 'Outcome · booked → calendar invite accepted within 24h. Tracks: persona, objections hit, rebuttals used, channel, time-to-book. Indicator of deal momentum: <12h time-to-book converts at 2.3x the 48h baseline.', metadata: { node_type: "outcome", outcome: "booked" } },
  { text: 'Outcome · pilot-started → customer in-product within 7 days. Strongest predictor of close (62% close rate at 90d). Pilot-started accounts have 3.1x higher ACV than direct-close accounts.', metadata: { node_type: "outcome", outcome: "pilot-started" } },
  { text: 'Outcome · re-engaged → not converted but follow-up scheduled. Use when buyer signals timing is wrong but interest exists. 28% re-engage after 30d. Best trigger to re-engage: product update announcement.', metadata: { node_type: "outcome", outcome: "re-engaged" } },
  { text: 'Outcome · lost → no path to re-engagement. Categorize by failure_reason for future learning: thin-dossier (31%), wrong-persona (24%), genuine-no-fit (18%), timing (16%), price (11%).', metadata: { node_type: "outcome", outcome: "lost" } },
];

export const DISTRIBUTION = {
  prior_calls: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "call_outcome").length,
  personas: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "persona").length,
  rebuttal_patterns: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "rebuttal_pattern").length,
  industry_playbooks: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "industry_playbook").length,
  temporal_patterns: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "temporal_pattern").length,
  journeys: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "journey").length,
  outcomes: DEMO_LEARNINGS.filter((l) => l.metadata.node_type === "outcome").length,
  total: DEMO_LEARNINGS.length,
};
